theme = "catppuccin-latte"


font-family = "JetBrains Mono"
font-feature = -calt


keybind=cmd+shift+k=scroll_page_up
keybind=cmd+shift+j=scroll_page_down
keybind=cmd+j=scroll_page_lines:3
keybind=cmd+k=scroll_page_lines:-3
