#!/usr/bin/env bash

yabai -m config top_padding 15
yabai -m config bottom_padding 15
yabai -m config left_padding 15
yabai -m config right_padding 15
yabai -m config window_gap 15

yabai -m config window_placement second_child

yabai -m config mouse_modifier fn

yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_follows_focus on
